export const productData = [
  {
    key: 1,
    brand: "Roadster",
    name: "Men Cotton Casual Shirt",
    color: "Red",
    price: 999,
    originalPrice: 2450,
    discount: "56%",
    sleeveLength: "Long Sleeves",
    collar: "Spread Collar",
    fit: "Regular Fit",
    print: "Solid",
    productCode: "2127876",
    seller: "some seller",
    wishlist: "false",
  },
  {
    key: 2,
    brand: "Roadster",
    name: "Men Cotton Casual Shirt",
    color: "Red",
    price: 989,
    originalPrice: 2450,
    discount: "56%",
    sleeveLength: "Long Sleeves",
    collar: "Spread Collar",
    fit: "Regular Fit",
    print: "Solid",
    productCode: "2127876",
    seller: "some seller",
    wishlist: "false",
  },
  {
    key: 3,
    brand: "Roadster",
    name: "Men Cotton Casual Shirt",
    color: "Black",
    price: 979,
    originalPrice: 2450,
    discount: "56%",
    sleeveLength: "Long Sleeves",
    collar: "Spread Collar",
    fit: "Regular Fit",
    print: "Solid",
    productCode: "2127876",
    seller: "some seller",
    wishlist: "false",
  },
  {
    key: 4,
    brand: "Roadster4",
    name: "Men Cotton Casual Shirt",
    color: "red",
    price: 969,
    originalPrice: 2450,
    discount: "56%",
    sleeveLength: "Long Sleeves",
    collar: "Spread Collar",
    fit: "Regular Fit",
    print: "Solid",
    productCode: "2127876",
    seller: "some seller",
    wishlist: "false",
  },
  {
    key: 5,
    brand: "Roadster5",
    name: "women Cotton Casual Shirt",
    color: "red",
    price: 959,
    originalPrice: 2450,
    discount: "56%",
    sleeveLength: "Long Sleeves",
    collar: "Spread Collar",
    fit: "Regular Fit",
    print: "Solid",
    productCode: "2127876",
    seller: "some seller",
    wishlist: "false",
  },
  {
    key: 6,
    brand: "Roadster6",
    name: "Men Cotton Casual Shirt",
    color: "red",
    price: 949,
    originalPrice: 2450,
    discount: "56%",
    sleeveLength: "Long Sleeves",
    collar: "Spread Collar",
    fit: "Regular Fit",
    print: "Solid",
    productCode: "2127876",
    seller: "some seller",
    wishlist: "false",
  },
];
